{{- if and (eq .Values.ingress.enabled true) (ne .Values.ingress.class "contour") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "foundry-vtt.fullname" . }}
  labels:
    app: {{ template "foundry-vtt.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
{{- if eq .Values.tls "external" }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false" # turn off ssl redirect for external.
{{- end }}
{{- if .Values.ingress.annotations }}
  {{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  {{- with .Values.ingress.class }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ template "foundry-vtt.fullname" . }}
            port:
              number: 80
{{- if eq .Values.tls "ingress" }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    {{- if eq .Values.ingress.tls.source "secret" }}
    secretName: {{ template "foundry-vtt.fullname" . }}-signed
    {{- else }}
    secretName: {{ template "foundry-vtt.fullname" . }}-ingress
    {{- end}}
{{- end }}
{{- end }}
