apiVersion: v1
kind: Secret
metadata:
  name: {{ template "foundry-vtt.fullname" . }}
  labels:
    app: {{ template "foundry-vtt.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  adminKey: {{ default "admin" .Values.foundryvtt.adminKey | b64enc }}
  {{- if .Values.foundryvtt.username }}
  username: {{ .Values.foundryvtt.username | b64enc }}
  {{- end }}
  {{- if .Values.foundryvtt.password }}
  password: {{ .Values.foundryvtt.password | b64enc }}
  {{- end }}
  {{- if .Values.foundryvtt.license_key }}
  license_key: {{ .Values.foundryvtt.license_key | b64enc }}
  {{- end }}
---
{{- if .Values.selfsigned }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "foundry-vtt.fullname" . }}-signed
  labels:
    app: {{ template "foundry-vtt.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  tls.crt: {{ .Values.selfsigned.cert | b64enc }}
  tls.key: {{ .Values.selfsigned.key | b64enc }}
type: kubernetes.io/tls
{{- end }}

---
{{- if eq .Values.foundryvtt.s3.awsConfig "file" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "foundry-vtt.fullname" . }}-aws
  labels:
    app: {{ template "foundry-vtt.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  aws-credentials.json: {{ .Values.foundryvtt.s3 | toJson | b64enc }}
{{- end }}

---
{{- if .Values.foundryvtt.turnConfigs -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "foundry-vtt.fullname" . }}-turn-configs
  labels:
    app: {{ template "foundry-vtt.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  turnConfigs.json: {{ toJson .Values.foundryvtt.turnConfigs | b64enc }}
{{- end }}
